### ISSUE TITLE
Lualine errors out upon closing harpoon list

### ISSUE THREAD

**Issue by ptdewey** [letieu/harpoon-lualine#12]
Setup: (All latest versions)
- lualine version 0a5a668
- lualine-harpoon version 07b5515
- harpoon2 version da326d0

Issue:
Upon closing an open harpoon list popup, with no files currently harpooned, lualine errors out with the following message
![Screenshot from 2024-04-07 16-25-58](https://github.com/letieu/harpoon-lualine/assets/57921252/0455bc2e-8e16-423d-9c7d-421fe1a0f836)

Fix:
I dug through the code a bit, and I was able to fix the issue by adding a nil check when fetching fetching the ith entry from the harpoon list. I will open a PR with my changes, feel free to merge it or add the changes yourselves.

Keep up the good work!

**Comment by letieu** [comment]
@all-contributors please add @ptdewey for code
