### ISSUE TITLE
Feature Request: Dynamic indicator support

### ISSUE THREAD

**Issue by duggthangs** [letieu/harpoon-lualine#16]
Hey everyone, amazing work bringing this plugin to life. One request that I have is adding support for dynamic indictors through a function call. My use case has some context that i store with every file (4 chars of file name) in harpoon and It would be really cool to have the ability to do something like this:
```lua
{
  'harpoon2',
  indicators = { 'h', 't', 'n', 's' },
  active_indicators = { '[H]', '[T]', '[N]', function(harpoon_entry)
    return harpoon_entry.context.file_short_name
  end },
  _separator = ' | ',
}
```

It would be nice for the indicators as well. I noticed I don't have trouble memorizing the indicator keys I have bound, but instead what file is on which key to quickly glance. 

Is this something interesting for this project or maybe there is a better way to handle my use case.

Thanks again 😄

**Comment by letieu** [comment]
Cool, let do it

**Comment by letieu** [comment]
@duggthangs added the feature 🗡️
