### ISSUE TITLE
loop in `for i ... harpoon:list:length()` causes no harpooned files to be shown when theres a missing index

### ISSUE THREAD

**Issue by allisonmeow** [letieu/harpoon-lualine#17]
i really cant write a pull request mostly because i don't know how i would fix this myself but the code seen
[here](https://github.com/letieu/harpoon-lualine/blob/d1b873c19b701fd80d60a67d086dbb3bcc4eb00e/lua/harpoon-lualine/init.lua#L16C1-L19C12) when you are for example deleting entry #1 of 3 (the index now starts at 2 so it causes an early return) causing it to show no entries

also also, dont you think theres a better way than converting the paths to full paths instead of getting both the relative paths (`vim.fn.expand('%:.')`)?

**Comment by letieu** [comment]
I can't reproduce this bug, can you explain more how to produce this bug.

And are you sure  you install `harpoon2` instead of `harpoon` on `main` branch

**Comment by letieu** [comment]
@all-contributors please add @hareki  for code
