### ISSUE TITLE
Special highlight for selected indicator

### ISSUE THREAD

**Issue by mageowl** [letieu/harpoon-lualine#18]
I would like to color the selected buffer green instead of using square brackets. Is it possible to add a highlight to the indicators?

**Comment by letieu** [comment]
you can follow this post, I will think about the feature :)

https://www.reddit.com/r/neovim/comments/1bf7fb7/comment/kv24fgl/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by mageowl** [comment]
Thanks for the quick response!
I went ahead and made a PR. (#19)
