### ISSUE TITLE
feature request: optional "Harpoon not loaded" message

### ISSUE THREAD

**Issue by Mephistophiles** [letieu/harpoon-lualine#9]
Hi! Thanks for great plugin! 

I'd like to suggest a feature for the plugin: the ability to customize or suppress the "Harpoon not loaded" message when the module is not loaded. In my workflow, Harpoon is loaded lazily, and until it's loaded, I'd prefer if the lualine section didn't display any information. Alternatively, having the option to customize this message would be really helpful.

Thanks for considering this enhancement! Let me know if you need any further clarification.

Best regards, Maxim

**Comment by letieu** [comment]
@Mephistophiles Thank for great idea, you can use `no_harpoon = "Your text"`

**Comment by Mephistophiles** [comment]
Oh, thank you!
